### ISSUE TITLE
Link to CSS Fonts 4, not 3, for same-document restrictions?

### ISSUE THREAD

**Issue by svgeesus** [w3c/woff#14]
WOFF2 says 

> User agents supporting the WOFF2 file format for linked fonts must respect the requirements of the CSS3 Fonts specification ([CSS3-Fonts] Section 4.1: The @font-face rule). In particular, such linked fonts are only available to the documents that reference them; they MUST NOT be made available to other applications or documents on the user's system.

Maybe the link should be updated to [CSS Fonts 4]https://www.w3.org/TR/css-fonts-4/#font-face-rule) which has the same text:

> Downloaded fonts are only available to documents that reference them. The process of activating these fonts must not make them available to other applications or to documents that don’t directly link to the same font. User agent implementers might consider it convenient to use downloaded fonts when rendering characters in other documents for which no other available font exists as part of the system font fallback procedure. However, this would cause a security leak since the contents of one page would be able to affect other pages, something an attacker could use as an attack vector. These restrictions do not affect caching behavior, fonts are cached the same way other web resources are cached.

No urgency, the text is the same, and CSS Fonts 4 is not a Rec.

**Comment by vlevantovsky** [comment]
I don't mind switching to CSS Fonts 4 at some point, but I am not sure if there are any rules about using references to WD from the Rec? Do we know when CSS Fonts 4 supposed to be promoted to CR?
