### ISSUE TITLE
Bug report: Variable CFF2 fonts stop working if WOFF2 compressed

### ISSUE THREAD

**Issue by svgeesus** [w3c/woff#19]
From https://twitter.com/mikekasprzak/status/1484641859079229440

> /facepalm

> It took way too much of my day to learn that Variable OpenType fonts compressed in WOFF2 format are unsupported in FireFox.

> Variable TrueType fonts in WOFF2, or uncompressed Variable OpenType fonts, no problem. 

> https://bugzilla.mozilla.org/show_bug.cgi?id=1302685

**Comment by svgeesus** [comment]
From https://twitter.com/svgeesus/status/1484928070385610759

> If there is a functional difference in the wild between an sfnt font and that same font WOFF2 compressed, @w3c
 webfonts WG wants to hear all about it.

**Comment by jfkthame** [comment]
Given the mozilla bug report mentioned, it sounds to me like someone may be confusing WOFF2 vs CFF2.

**Comment by svgeesus** [comment]
Hi @jfkthame yes I suspect so

From https://twitter.com/KhaledGhetas/status/1484923360412934158

> WOFF2 shouldn’t be a factor, on the same systems OTF variable fonts should equally fail. If the Linux system is using an older version of FreeType that does not support CFF2, it would fail for the same reasons as Windows.

**Comment by svgeesus** [comment]
https://twitter.com/mikekasprzak/status/1484878193035255812

> Again, WOFF2 TTF Variable fonts work, but not WOFF2 OTF Variable fonts. Also despite the conversation about Windows at the end, I get the exact same error as buddy on Linux: Firefox chokes on one index validation thing.

**Comment by jfkthame** [comment]
I'm finding it difficult to follow the twittering, but it looks like maybe this is the conclusion:
https://twitter.com/mikekasprzak/status/1485022131826171909?cxt=HHwWioC9sdnw7ZspAAAA

> Yes, but I must have mixed up my deployments and made the wrong conclusion. I created a standalone test a few hours ago and couldn't reproduce compressed vs uncompressed. So it's not the compression. The issue is the lack of CFF2 support in Firefox (per bugzilla).

In which case, nothing to see here...

**Comment by svgeesus** [comment]
Thanks, I was also trying to follow the Twitter thread.

I agree, WOFF2 is a red herring here and the actual issue is lack of CFF2 support on some platforms/some browsers. 

I also tried to find out whether latest FreeType supports CFF2, it seems it does although the documentation is out of date and doesn't mention any CFF2 support.
