### ISSUE TITLE
UInt32 unspecified in WOFF2

### ISSUE THREAD

**Issue by svgeesus** [w3c/woff#4]
Johannes Hägele wrote:

> I'm currently reading and working with the WOFF2 Spec (https://www.w3.org/TR/WOFF2/)
In the spec you are working with the Data Type "UInt32" (for example at the WOFF2 Header section https://www.w3.org/TR/WOFF2/#woff20Header).
> But in the section "Data Types" (https://www.w3.org/TR/WOFF2/#DataTypes) this data type is not specified.
I  have also checked the WOFF1 spec and there it is specified. (https://www.w3.org/TR/2012/REC-WOFF-20121213/#OverallStructure)
> Is this a mistake on your side (W3) or do i understand something wrong?

**Comment by svgeesus** [comment]
I responded

> Hi Johannes,
>
> Thanks for the report. UInt32 is simply an unsigned 32-bit integer. However, you are correct that this should have been explicitly stated, as it was in WOFF1.
>
> I have raised an issue on our GitHub repository
https://github.com/w3c/woff/issues/4
>
> and further discussion will take place there. I expect that we will simply publish an erratum for this, copying the definitions from WOFF1.
>
> Thanks again for taking the time to report this.

**Comment by vlevantovsky** [comment]
I agree, and the missing description of the simple datatype can be easily addressed by publishing an erratum.

**Comment by svgeesus** [comment]
The [erratum has been published](https://www.w3.org/Fonts/REC-WOFF2-20180301-errata.html)

**Comment by svgeesus** [comment]
Now edited in as Candidate Correction
