### ISSUE TITLE
WOFF2: Language does not indicate if on/off curve bit of flags is set or cleared to indicate on/off curve

### ISSUE THREAD

**Issue by wezm** [w3c/woff#5]
https://github.com/w3c/woff/blob/4b08e75f0e7ae78353985d6b6b109438f6beb921/woff2/index.html#L1077

> The most significant bit of a flag indicates whether the point is on- or off-curve point, the remaining seven bits of the flag determine the format of X and Y coordinate values and specify 128 possible combinations of indices that have been assigned taking into consideration typical statistical distribution of data found in TrueType fonts.

This does not indicate whether the bit is set or cleared to indicate whether the point is on or off curve. It turns out that it's actually cleared, which is opposite to the non-transformed `glyf` table.

From [MicroType](https://www.w3.org/Submission/2008/SUBM-MTX-20080305/#TripletEncoding):

> We use one bit of the first byte to indicate whether the point is an on- or off-curve point (if the most significant bit is 0, then the point is on-curve).

[OpenType](https://docs.microsoft.com/en-us/typography/opentype/spec/otff):

> ON_CURVE_POINT | Bit 0: If set, the point is on the curve; otherwise, it is off the curve.

**Comment by vlevantovsky** [comment]
Should be defined [the same way as in MTX submission](https://www.w3.org/Submission/MTX/#SimpleCTF).

**Comment by svgeesus** [comment]
OK so the erratum is just adding the parenthetical

```
(if the most significant bit is 0, then the point is on-curve)
```

**Comment by svgeesus** [comment]
Now edited in as Candidate Correction

**Comment by svgeesus** [comment]
MTX says:

> We use one bit of the first byte to indicate whether the point is an on- or off-curve point (if the most significant bit is 0, then the point is on-curve). 

So this is what existing implementations do, and the omission of the parenthetical clarification in the WOFF 2 spec was just an oversight.
