### ISSUE TITLE
WOFF2: Step 2a of Decoding of Composite Glyphs refers to itself

### ISSUE THREAD

**Issue by wezm** [w3c/woff#6]
https://github.com/w3c/woff/blob/4b08e75f0e7ae78353985d6b6b109438f6beb921/woff2/index.html#L1036

> 1a. Read a UInt16 from compositeStream. This is interpreted as a component flag word as in the TrueType spec. Based on the flag values, there are between 4 and 14 additional argument bytes, interpreted as glyph index, arg1, arg2, and optional scale or affine matrix.
> 
> 2a. Read the number of argument bytes as determined in step **2a** from the composite stream, and store these in the reconstructed glyph. If the flag word read in step **2a** has the FLAG_MORE_COMPONENTS bit (bit 5) set, go back to step **2a**. 

I think the first two references I've highlighted in bold are actually referring **1a**, I'm less confident about the third one, but it might be in the same situation.

**Comment by vlevantovsky** [comment]
Confirmed bug, the references need to be corrected. 
At some point in time the spec was restructured with the step 1/1a (being common for both simple and composite glyphs) moved into a separate paragraph of "Reconstruction of Glyph Records" section, which caused the renumbering of decoding steps for both simple and composite glyphs. The references to step 2a were left in their original form, all need to be corrected to point to step 1a. 
(Note to self - the references to steps 4 and 5 from the description of step 3a are correct.)

**Comment by svgeesus** [comment]
Still needs to be done.

**Comment by vlevantovsky** [comment]
Yes, all these references in 2a should point to step 1a.

**Comment by vlevantovsky** [comment]
@garretrieger can you please check that the decoder implementation is doing the right things?

**Comment by garretrieger** [comment]
I'll double check the implementation to make sure it matches the proposed update.

**Comment by garretrieger** [comment]
Confirmed that the decoder implementation is going back to step 1a as expected.
