### ISSUE TITLE
Transformed 'glyf' table version is underspecified

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/woff#9]
Other than declaring the version field to be present and set to zero, there is nothing in the WOFF2 recommendation about its purpose and / or intended use. 
It is currently defined as `Fixed version` field, and we are planning to split it to two separate UInt16 fields: `UInt16 version` and `UInt16 optionFlags`. It would be logical to say something about how this `version` field is intended to be used.

**Comment by svgeesus** [comment]
On today's call we decided to make the version reserved, and not to increment it. Spec will say to ignore the contents.

**Comment by svgeesus** [comment]
Now done.
